version: "3.3"
services:
  python:
    build: ./python/
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - SCOPE=${SCOPE}
      - SECRET=${SECRET}
    networks:
      network:
        ipv4_address: 10.6.0.7
  react:
    build: ./react/
    restart: always
    ports:
      - "18080:80"
      # - "443:443"
    networks:
      network:
        ipv4_address: 10.6.0.8

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16