version: "3.3"
services:
  python:
    build: ./python/
    restart: always
    networks:
      network:
        ipv4_address: 10.5.0.7
  angular:
    build: ./react/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      network:
        ipv4_address: 10.5.0.8

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16