/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/callback": {
    get: {
      parameters: {
        query: {
          /** The authorization code from Spotify. */
          code: string;
        };
      };
      responses: {
        /** The username of the logged in user. */
        200: {
          schema: {
            /** @description The username of the logged in user. */
            username?: string;
          };
        };
      };
    };
  };
  "/create_playlist": {
    post: {
      parameters: {
        body: {
          body: {
            /** @description The list of artists to include in the playlist. */
            artists?: string[];
            /** @description The name of the playlist to be created. */
            name?: string;
          };
        };
      };
      responses: {
        /** A message indicating that the playlist was created successfully. */
        200: {
          schema: {
            /** @description A message indicating that the playlist was created successfully. */
            message?: string;
          };
        };
        /** No artists provided. */
        400: unknown;
        /** You must login first. */
        401: unknown;
        /** An error occurred. */
        500: unknown;
      };
    };
  };
  "/login": {
    get: {
      responses: {
        /** The authorization URL for Spotify login. */
        200: {
          schema: {
            /** @description The authorization URL. */
            auth_url?: string;
          };
        };
      };
    };
  };
  "/search_artist": {
    get: {
      parameters: {
        path: {
          /** The name of the artist to search for. */
          query: string;
        };
      };
      responses: {
        /** A list of artists matching the query. */
        200: {
          schema: unknown[];
        };
        /** No query provided. */
        400: unknown;
        /** You must login first. */
        401: unknown;
        /** An error occurred. */
        500: unknown;
      };
    };
  };
}

export interface definitions {}

export interface operations {}

export interface external {}
